name: Projeto TechChallenge CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      # Checkout código
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuração do ambiente .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: './01_WebApi/packages.lock.json'

      # Restauração e compilação
      - name: Restore and Build
        run: |
          dotnet restore ./Fase1TechChallenge.sln
          dotnet build --no-restore ./Fase1TechChallenge.sln

  test:
    runs-on: ubuntu-latest
    name: Test Project
    needs: build
    steps:
      # Checkout código novamente no job de teste
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuração do ambiente .NET Core no job de teste
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Executar testes e coletar resultados
      #- name: Run Tests
      #  run: |
      #    dotnet test ./05_UnitTest/05_UnitTest.csproj --logger trx --results-directory "TestsResults" --no-restore --no-build --collect "Code Coverage"

      # Upload dos resultados dos testes
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestsResults