name: primeiro workflow Projeto techchanllenge GitHub Actions para Build Project

on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .NET core
            uses: actions/setup-dotnet@v4
            with:
               dotnet-version: '8.x'
               cache: true
               cache-dependency-path: './01_WebApi/packages.lock.json'
          
          - name: Build
            run: |
               dotnet restore ./Fase1TechChallenge.sln
               dotnet build --no-restore ./Fase1TechChallenge.sln
               