name: primeiro workflow Projeto techchanllenge GitHub Actions para Build Project

on:
  push:
    branches:
      - main
  pull_request:
     branches:
       - main
       
  workflow_dispatch:

jobs:
#add controle de vercionamento
  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 #historico de commits, assim fazendo o recalculo da versão

      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main #podendo variar com main master
          prefix: v

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a "${{ steps.version.outputs.version }}" -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
          if: github.ref == 'refs/heads/main'


  build:
    runs-on: ubuntu-latest
    name: Build Project
    steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .NET core
            uses: actions/setup-dotnet@v4
            with:
               dotnet-version: '8.x'
               cache: true
               cache-dependency-path: './01_WebApi/packages.lock.json'
          
          - name: Build and test
            run: |
               dotnet restore ./Fase1TechChallenge.sln
               dotnet build --no-restore ./Fase1TechChallenge.sln
               dotnet test ./Fase1TechChallenge.sln --no-restore --no-build --logger trx --results-directory "TestsResults"
          
          - uses: actions/upload-artifact@v4
            with:
                name: dotenet-test-results
                path: TestsResults
               